### ISSUE TITLE
Implications of making IO default in 0.12 on purescript-react

### ISSUE THREAD

**Issue by RAbraham** [purescript-contrib/purescript-react#116]
Hi,
Regarding Phil's [tweet](https://twitter.com/paf31/status/908760073303764993) about IO being the default in 0.12, will all of `purescript-react`'s signatures (e.g. `readState`, `writeState`) change? I don't know if 0.12 is coming out next or much later down the year though.

**Comment by paf31** [comment]
We have a few options:

- continue to use `Eff` in this library, to keep the current benefits
- achieve the same thing using some other technique
- just use `IO` and assume the user does the right thing

**Comment by natefaubion** [comment]
I vote for 3.

**Comment by natefaubion** [comment]
For some clarification, the effect tracking is way more trouble than it's worth _as-is_ as soon as you need to take handlers as props. The other alternative would be to add the indexed capabilities to the "ReactThis" context, but this would require some sort of ST like variable to restrict it's scope. This again, is not worth it.

**Comment by alexjg** [comment]
Is there any plan for the upgrade to 0.12? I would love to help out, especially if it's just a case of mechanically remove the effect rows as that seems pretty straightforward :).

**Comment by natefaubion** [comment]
@alexjg there is a currently pending PR with updates for 0.12 and React 16.3
