### ISSUE TITLE
Strange `preventDefault` & `stopPropagation` types

### ISSUE THREAD

**Issue by spicydonuts** [purescript-contrib/purescript-react#120]
Both of these functions have the type `forall eff a. Event -> Eff eff a`.  What `a` is this?  Seems like accidentally coercing that to something really unsafe would be easy, and really difficult to track down later.  Just want to make sure this isn't necessary for some reason before making a PR (to `forall eff. Event -> Eff eff Unit`).

**Comment by ethul** [comment]
Closed by #121
