### ISSUE TITLE
Children should be a ReactRender instance

### ISSUE THREAD

**Issue by natefaubion** [purescript-contrib/purescript-react#127]
Likewise, `getChildren` should just yield `Children`.

**Comment by unclechu** [comment]
Maybe this is related:
https://github.com/purescript-contrib/purescript-react/blob/14b4c22de2379437bba52e3dbbd3b76da392e0c0/src/React.purs#L415-L417
Children here is `Array ReactElement` but maybe it should be another `ReactRender` instance?

**Comment by ethul** [comment]
Closing. Fixed via #137
