### ISSUE TITLE
document `npm install`

### ISSUE THREAD

**Issue by alicebob** [purescript-contrib/purescript-react#138]
When using this in a browser you need to run `npm install react react-dom` with specific react versions. Also `pulp bundle` isn't good enough anymore and you will need to use `pulp browserify`.
I did not find this documented anywhere (coming from the Thermite repo). It would be incredible helpful if that was mentioned in the README here and/or at Thermite.

See also
https://stackoverflow.com/questions/42763558/integrating-react-components-with-pux-where-does-require-come-from
https://stackoverflow.com/questions/43337332/electron-purescript-thermite

**Comment by ethul** [comment]
I agree that it would be helpful to mention that this module depends on the react library. Having an example of using NPM as one option to satisfy the dependency would be a nice addition to the README.

Thanks for bringing this up.

**Comment by alicebob** [comment]
:confetti_ball: thanks!

**Comment by ethul** [comment]
Welcome!
