### ISSUE TITLE
Remove createFactory?

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-react#142]
Is there a point of having createFactory? it just call's `createElement`

https://github.com/facebook/react/blob/master/packages/react/src/ReactElement.js#L260-L273

**Comment by safareli** [comment]
based on current definition of createFactory in react, we can define it here as:
`createFactory cls props = createElement cls props mempty`

and as it has no advantages we can just remove it.

**Comment by paulyoung** [comment]
This came up in https://github.com/purescript-contrib/purescript-react/issues/128, and I thought it was removed in https://github.com/purescript-contrib/purescript-react/pull/129.

**Comment by safareli** [comment]
ah i was looking at old version of this lib :d
