### ISSUE TITLE
New API is confusing (to me, anyway)

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-react#153]
I can't figure out why this isn't working:

```purescript
ui = D.div' [ createLeafElement cls {} ]
```

where

```purescript
cls :: ReactClass {}
```

I get 

```
  133    ui = D.div' [ createLeafElement (explore together) {} ]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  No type class instance was found for
  
    Prim.Row.Union t0
                   t2
                   ()
```

**Comment by natefaubion** [comment]
Your source and error don't appear to align. Your error says your component is `explore together` is the component, not `cls`. I'm assuming you probably have a forall on props. `createElement` has constraints to reflect the API requirements of `key` and `ref`, which can be confusing. If you have a forall, you'll have to instantiate it to something before passing it to `createElement`. The old behavior is available as `unsafeCreateElement`. This is worth documenting.

**Comment by paf31** [comment]
For some reason, I can't use `unsafeCreateLeafElement`, I get 

```
  Cannot import value unsafeCreateLeafElement from module React
  It either does not exist or the module does not export it.
```

but it clearly exists and is exported so I don't know what's going on.

**Comment by paf31** [comment]
Ignore that, sorry, it works when I use the latest tag.
