### ISSUE TITLE
`props` vs `Record props`

### ISSUE THREAD

**Issue by safareli** [purescript-contrib/purescript-react#161]
In types of `*component*` functions we have `Record props` instead of `props`, why is that the case?

for example Record from writeState can be removed (pr https://github.com/purescript-contrib/purescript-react/pull/160) and I suppose it could be done for some of this `*component*` functions too.

**Comment by natefaubion** [comment]
React does not treat props and state parametrically. If we wanted a parametric type we would have to box it anyway (which is what this library used to do), and is what [`purescript-react-basic` does](https://github.com/lumihq/purescript-react-basic/blob/7fb83512b976523d1c9def90617e0e143bdaea1b/src/React/Basic.js#L11-L14) but this breaks things like `pureComponent`, or any new utilities like `memo`. We would have to write our own versions which deal with that. My impression of `purescript-react` is that it attempts to write typed bindings for the API as is, for better or for worse.

**Comment by safareli** [comment]
:( will close #160 then. thanks for the clarification
