### ISSUE TITLE
Direction of this library

### ISSUE THREAD

**Issue by joneshf** [purescript-contrib/purescript-react#25]
Where are we heading with this? Are we sticking close to React semantics? Or are we attempting to wrap them up in our own special way while just using React's machinery underneath?

With the stuff we have now, it's hard to see that it's actually using React underneath for me. But it becomes obvious when react complains about an invariant violation. But it also seems like we're trying to abstract away some of the React details by managing the context with `__current` and implicitly wrapping state in an object and whatnot.

For example, it's hard to find the mapping between `createClass` and our `mkUI` function. Without looking at the source, it's tough to know how to convert a js program into a ps program. 

I understand that most of this could be cleared up with some documentation, but I still think it's something we should think about and discuss.

Maybe the better questions is: What should this library be, a thin wrapper around React or a View implementation that just uses React under the hood?

To me, the first seems like what someone would expect when they see `purescript-react`. And I feel it has its place if that's not what we want to do. But I also feel that the second option is also very important (more important maybe?) and should be implemented at some point. Although, with a stronger foundation that doesn't rely on runtime checks for things that can be verified statically.

**Comment by seanhess** [comment]
So what ended up happening with this?

**Comment by paf31** [comment]
Is this library still alive? Does it even still build? :) If not, should we put a warning sticker on the README?

**Comment by garyb** [comment]
Yeah, I think we should deprecate it, perhaps linking to newer efforts like `thermite` and `purescript-react-simple`.

**Comment by paf31** [comment]
Closing this, since the library has been updated for a while now, it's maintained again, and `thermite` uses it as a base.
