### ISSUE TITLE
Maintenance going forward

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-react#33]
We're trying to find maintainers for `purescript-contrib` libraries. https://github.com/purescript/purescript/issues/1156

Would anyone like to become the maintainer of this library?

**Comment by paf31** [comment]
No takers? Is this deprecated then?

**Comment by paf31** [comment]
I think there is definitely a good case for a low-level set of React bindings, even if it's just so for use in higher-level APIs like `thermite`.

**Comment by joneshf** [comment]
Yeah, I'm passing, but I feel the same way. I think this library could be a great thing to have, but I just don't have the time to put into it.

It'd be a nice lib for someone who knows react well, has a vested interest in it and wants to learn ps.

**Comment by paf31** [comment]
I wouldn't mind spending some time on it, but I'd definitely want to change the way `this` is treated.

**Comment by paf31** [comment]
Ok, I've updated the library for the 0.7 release. I'll spend some more time on the API soon.
