### ISSUE TITLE
Is React 0.13.x supported?

### ISSUE THREAD

**Issue by AlexeyRaga** [purescript-contrib/purescript-react#34]
The current version of React is 0.13.3, but when I run the example it doesn't work against React 0.13.3.

The problem is that in 0.12.x React would give a warning (and that's what I see if I run the example against 0.12.2):

    Warning: Something is calling a React component directly. Use a factory or JSX instead. 
    See: http://fb.me/react-legacyfactory

But in 0.13.x React has removed `renderComponent`, `renderComponentToString` and `renderComponentToStaticMarkup` functions which were deprecated in 0.12.x, but still used by the example.

Instead, the new "correct" way would be:

    React.render(React.createFactory(MyComponent)(config), node)

But I don't know how to express it in `purescript-react`. Is there a way?

**Comment by paf31** [comment]
It's not supported right now, but I'd be happy to take a PR to modify the FFI to use it.

**Comment by haf** [comment]
+1 on this, from a newbie who has this as his use-case for starting to use PureScript =)

**Comment by yemi** [comment]
+1
