### ISSUE TITLE
Unknown module DOM

### ISSUE THREAD

**Issue by danse** [purescript-contrib/purescript-react#35]
Hello, i was trying the shortest path for evaluating this library. Here is what i did:

- scaffold a new project with Pulp, the project builds and tests successfully
- install this library with `pulp dep i purescript-react --save`
- copy the example from the readme here to `src/Main.purs`
- run `pulp build`

I get the following error:

```sh
 purescript $ pulp build
* Building project in /Users/francesco/experiments/purescript
Error:
Error in module React:
Error at /Users/francesco/experiments/purescript/bower_components/purescript-react/src/React.purs line 52, column 1 - line 54, column 1:
  Unknown module DOM
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownModule for more information, or to contribute content related to this error.

* ERROR: Subcommand terminated with error code 1
```

I looked for `DOM` in Pursuit, but it does not seem to be a symbol exported by any package. I am using `psc` 0.7 and `purescript-react` 1.0

**Comment by paf31** [comment]
What's in the `bower_components` directory?

**Comment by danse** [comment]
```sh
 purescript $ lt bower_components/
total 0
drwxr-xr-x  8 francesco  staff  272 Jul 29 14:10 purescript-prelude/
drwxr-xr-x  8 francesco  staff  272 Jul 29 14:10 purescript-eff/
drwxr-xr-x  8 francesco  staff  272 Jul 29 14:10 purescript-console/
drwxr-xr-x  8 francesco  staff  272 Jul 29 14:21 purescript-st/
drwxr-xr-x  8 francesco  staff  272 Jul 29 14:21 purescript-functions/
drwxr-xr-x  9 francesco  staff  306 Jul 29 14:57 purescript-react/
```

**Comment by paf31** [comment]
Strange, you should have `purescript-dom` there too:

https://github.com/purescript-contrib/purescript-react/blob/master/bower.json#L20

**Comment by danse** [comment]
Well, it is a dev dependency. This might mean that it is not considered necessary for using the package as a library

**Comment by paf31** [comment]
Doh, will fix, thanks.

**Comment by danse** [comment]
cool, thanks!

**Comment by paf31** [comment]
Ok, 0.1.1 released.

**Comment by danse** [comment]
wow, that was fast :)

**Comment by paf31** [comment]
Thank you GitHub file editor :P
