### ISSUE TITLE
Parameterize ReactThis by props and state

### ISSUE THREAD

**Issue by ethul** [purescript-contrib/purescript-react#41]
I am wondering if `ReactThis` should be parameterized by `props` and `state`. For instance,

```purescript
foreign import data ReactThis :: * -> * -> *
```

For instance, in the `readState` function, we currently can pass any `ReactThis`, but I think it should only take the `ReactThis` that is a reference to the state to read. For instance,

```purescript
foreign import readState :: forall props state write eff. ReactThis props state -> Eff (state :: ReactState (Read write) state | eff) state
```

I am not completely sure about this change, but I wanted to bring it up for discussion.

**Comment by paf31** [comment]
:+1: Sounds good.

**Comment by ethul** [comment]
Great. I will send a PR for this.
