### ISSUE TITLE
DOM elements props vs custom elements props

### ISSUE THREAD

**Issue by BartAdv** [purescript-contrib/purescript-react#43]
Why DOM elements use Array Props: `a :: Array Props -> Array ReactElement -> ReactElement`
whereas `createElement` expects just a record: `createElement :: forall props. ReactClass props -> props -> Array ReactElement -> ReactElement` ?

**Comment by paf31** [comment]
Due to the relatively large number of available props on React elements, it's easier to provide them as an array if we want to keep type-safety. Maybe something like `purescript-options` is another option. User components pick their own `props` type, so they are not constrained in this way.
