### ISSUE TITLE
Potentially migrate to setState instead of replaceState

### ISSUE THREAD

**Issue by ethul** [purescript-contrib/purescript-react#48]
Currently, `replaceState` is used in the `writeState` function.
https://github.com/purescript-contrib/purescript-react/blob/cbe6f58645cc3f53a608ac9e4e08e6b375866528/src/React.js#L35-L37

However, from the docs, `replaceState` may be removed in the future.
https://facebook.github.io/react/docs/component-api.html#replacestate

Since the state is wrapped in `{state: state}` I believe we'd get the same behaviour even though `setState` does a shallow merge instead of a complete state replacement.

I hope to have a chance to prepare a PR for this. But I wanted to note it down.

**Comment by paf31** [comment]
:+1: Sounds good.
