### ISSUE TITLE
Adopt events from `DOM.DOM.Event`

### ISSUE THREAD

**Issue by danse** [purescript-contrib/purescript-react#57]
In order to avoid defining the whole typology again. See the discussion on https://github.com/paf31/purescript-thermite/issues/49

**Comment by paf31** [comment]
:+1: Definitely.

**Comment by danse** [comment]
Nope! :)

Sorry, i just found out that React events [are different](https://facebook.github.io/react/docs/events.html), which is actually good, because this way they eliminate differences depending on the Browser.

The docs say that they aim to keep the same interface as native events, but i am afraid that using exactly the same type of native events would be misleading.

**Comment by ethul** [comment]
Are we okay keeping events separate due to the difference? Is this issue safe to close?

**Comment by danse** [comment]
I am okay with keeping them separate, and closing this issue is fine by me. I had a look at the [code from React](https://github.com/facebook/react/blob/422b4e105c7ac12272b7f776501e630ce89b90fb/src/renderers/dom/client/syntheticEvents/SyntheticEvent.js), and it does not seem that native methods are reused. Skimming through it, i think that all methods are redefined, thus even deriving a class from the other wouldn't be a accurate mapping

**Comment by ethul** [comment]
Thanks for the update and digging in to this. Closing this issue.
