### ISSUE TITLE
Bug in `mkDom`?

### ISSUE THREAD

**Issue by jasonzoladz** [purescript-contrib/purescript-react#58]
I think the changes related to the addition of `IsDynamic` have introduced a bug to the `mkDom` function, which breaks `createElement` in the `where` clause.  See below.

<img width="988" alt="screen shot 2016-01-31 at 6 43 08 pm" src="https://cloud.githubusercontent.com/assets/8467728/12706121/e324589a-c84b-11e5-9b7e-0b27164207d2.png">
<img width="643" alt="screen shot 2016-01-31 at 6 43 56 pm" src="https://cloud.githubusercontent.com/assets/8467728/12706122/e6e85c06-c84b-11e5-8922-653085ba3e04.png">

**Comment by ethul** [comment]
Thanks for the report. I will take a look.

**Comment by ethul** [comment]
Actually, I think we have a module naming issue. Can you try to clean your
purescript output and recompile with "--require-path=../"

**Comment by jasonzoladz** [comment]
Thanks for the quick response.

I just tried to compile and load `purescript-react-example` (instead of my own project) and had the same issue, using pulp 8.0.  Then I downgraded to pulp 7.0 and it worked. . .  Closing while I figure out what is going on.  I hate JS tooling.

**Comment by ethul** [comment]
Thanks for digging into this. Please keep me posted.

**Comment by jasonzoladz** [comment]
Really strange behavior.  Back at pulp 8.0 and I have to:

 1) delete "output"
 2) "pulp build -r=../"
 3)  "pulp browserify --to bundle.js"

on every source change, else I get errors like the one below . . .  Any clue?

<img width="651" alt="screen shot 2016-01-31 at 8 15 20 pm" src="https://cloud.githubusercontent.com/assets/8467728/12706699/f9a04618-c857-11e5-8efb-7a65c3c160b7.png">

**Comment by ethul** [comment]
Are you using -r=../ with watch enabled for pulp? Is there a way to
check if it is passed through to psc?

**Comment by ethul** [comment]
Also, can you paste the generated JavaScript before step 3?

**Comment by jasonzoladz** [comment]
I haven't been using watch for this.  Let me see if it's passed through to psc.

Here's the index.js before step 3:

```javascript
// Generated by psc version 0.8.0.0
"use strict";
var Prelude = require("Prelude");
var Control_Monad_Eff = require("Control.Monad.Eff");
var Control_Monad_Eff_Console = require("Control.Monad.Eff.Console");
var Data_Maybe_Unsafe = require("Data.Maybe.Unsafe");
var Data_Nullable = require("Data.Nullable");
var DOM = require("DOM");
var DOM_HTML = require("DOM.HTML");
var DOM_HTML_Types = require("DOM.HTML.Types");
var DOM_HTML_Window = require("DOM.HTML.Window");
var DOM_Node_NonElementParentNode = require("DOM.Node.NonElementParentNode");
var DOM_Node_Types = require("DOM.Node.Types");
var React = require("React");
var ReactDOM = require("ReactDOM");
var React_DOM = require("React.DOM");
var React_DOM_Props = require("React.DOM.Props");
var hello = React.createClass(React.spec(Prelude.unit)(function (ctx) {
    return function __do() {
        var v = React.getProps(ctx)();
        return React_DOM.h1([ React_DOM_Props.className("Hello"), React_DOM_Props.style({
            background: "lightgray"
        }) ])([ React_DOM.text("Hello, "), React_DOM.text(v.name), React.createElement(React.createClassStateless(function (props1) {
            return React_DOM["div'"]([ React_DOM.text(" World!  " + props1.test) ]);
        }))({
            test: "test"
        })([  ]) ]);
    };
}));
var elm$prime = function __do() {
    var v = DOM_HTML.window();
    var v1 = DOM_HTML_Window.document(v)();
    var v2 = DOM_Node_NonElementParentNode.getElementById("pip")(DOM_Node_Types.documentToNonElementParentNode(DOM_HTML_Types.htmlDocumentToDocument(v1)))();
    return Data_Maybe_Unsafe.fromJust(Data_Nullable.toMaybe(v2));
};
var main = (function () {
    var ui = React_DOM["div'"]([ React.createFactory(hello)({
        name: "World"
    }) ]);
    return Prelude["void"](Control_Monad_Eff.functorEff)(Prelude[">>="](Control_Monad_Eff.bindEff)(elm$prime)(ReactDOM.render(ui)));
})();
module.exports = {
    "elm'": elm$prime, 
    main: main, 
    hello: hello
};
```

**Comment by ethul** [comment]
Notice the require statements. They should start with ../

**Comment by jasonzoladz** [comment]
Yep. 

The problem is that the three steps don't always work.  I'm starting to get this (see below) randomly, so it looks like a module loading problem.  Yikes.

Thanks for your help.

<img width="883" alt="screen shot 2016-01-31 at 8 55 13 pm" src="https://cloud.githubusercontent.com/assets/8467728/12707081/f4e83c20-c85c-11e5-95e2-284729639ddf.png">

**Comment by ethul** [comment]
Welcome. Do you know where the problem is stemming from?

**Comment by jasonzoladz** [comment]
Unfortunately no.  But I have to put it to bed for the night or my wife will bludgeon me.

I'll dig into this tomorrow.

**Comment by ethul** [comment]
Got it. Keep me posted on the issue.

**Comment by jasonzoladz** [comment]
The problem appears multifaceted:

- a change of `require-path` doesn't cause a rebuild:  https://github.com/purescript/purescript/issues/1836

- when I try to rely on the $NODE_PATH, the case-insensitive mac file system causes conflicts (react/index.js vs. React/index.js; react/foreign.js vs. React/foreign.js)

- right now, dependency management for PS is a house of cards

**Comment by hdgarrood** [comment]
The fact that it says "cannot find module =../Prelude" makes me think that the equals sign has been interpreted as a part of the `--require-path` value. Perhaps the equals is only required when you use the long form? Does it fix it if you use the long version: `--require=path=../`? Maybe `-r ../` would also be worth trying.

**Comment by hdgarrood** [comment]
Also, what does this have to do with dependency management?

**Comment by jasonzoladz** [comment]
@hdgarrood:  `-r ../` doesn't work

@hdgarrood:  I meant to write package management.  And it was more of an expression of frustration with packaging and distribution in PS than a comment specific to this issue.  The use of a React wrapper is a trivial undertaking in ScalaJS and ClojureScript.

**Comment by hdgarrood** [comment]
It's quite difficult to help when you only answer one of the 3 questions I asked, and even that answer only has 3 words.

> The use of a React wrapper is a trivial undertaking in ScalaJS and ClojureScript

Well, both ScalaJS and ClojureScript have been around for a while longer than PureScript has. I'm sure there would have been a stage in both of their developments when tasks such as this one would have been painful, too.

Anyway, I think what's happening is that `pulp browserify` effectively does `pulp build` first. Unfortunately, since the passthrough arguments on `pulp browserify` go to `psc-bundle`, there's no way of specifying `--require-path` for the invocation of `psc`. So that would explain why you have to `pulp build -r ../` every time beforehand.

**Comment by jasonzoladz** [comment]
It was two words.  :)  And for the reason you stated, the other two variants don't work either.

**Comment by hdgarrood** [comment]
What about the following workflow instead? I think it would avoid the module name clashing issue. It might be a little slow, as you're doing DCE every time, but I think it should at least work.

```
$ pulp build --to tmp/browserify.js
$ browserify tmp/browserify.js > bundle.js
```

This would use the default (empty) `--require-path` option. Make sure you `rm -r output` first to make sure there are no modules using `../`.

**Comment by jasonzoladz** [comment]
I very much appreciate the help.  I'll try that and report back.

**Comment by ethul** [comment]
To put another option on the table, there is also the possibility to use webpack:
https://www.npmjs.com/package/purescript-webpack-plugin
https://www.npmjs.com/package/purs-loader

Just sayin'

**Comment by jasonzoladz** [comment]
Thanks @ethul, I'll give that a go as well.

**Comment by ethul** [comment]
Great!

**Comment by hdgarrood** [comment]
Yeah, webpack could well be a better choice here, at least for now ;)

I think this is a problem that needs addressing in Pulp somehow, but I'm not quite sure exactly how yet.

**Comment by ethul** [comment]
For webpack, note https://github.com/purescript/purescript/issues/1794

So it will probably only work using PureScript 0.8

**Comment by jasonzoladz** [comment]
Huzzah!!

@hdgarrood:  Your approach works.

@ethul:  As does yours.

Awesome.  Thanks again.  (I recently built an MVP for a non-profit in ScalaJS with `scalajs-react` and `diode`.  The libraries are very well made but I don't love Scala.  I hope to use PureScript instead.  Getting npm integrated was the first step.)

**Comment by ethul** [comment]
Thanks for giving them a go. Glad they both work for you!
