### ISSUE TITLE
"React" module name clashes with JavaScript one

### ISSUE THREAD

**Issue by cbaatz** [purescript-contrib/purescript-react#59]
In trying to incrementally move a JS React UI to PureScript using this wrapper, I discovered that the "React" module namespace clashes with the default "react" package when bundled together with (at least) Browserify. That is, when the compiled code requires "React" it finds the native JS version rather than the PureScript module which fails with a runtime error since the native module and this are clearly different.

Regardless of the above problem (which I can probably solve by aliasing the native react module and updating all imports), is "React" really the right module name? I would have thought something like "Web.React" or similar would be more appropriate?

**Comment by ethul** [comment]
I agree that the name clash is not ideal. One way to resolve this is to use the `--require-path` option for `psc`. It can be set to `../` for example. It's a good question whether `React` is the right module name. I am open to discussing some ideas. However, depending on purescript/purescript#1698 the naming might not be an issue.

**Comment by cbaatz** [comment]
Thanks! I didn't know about `--require-path`. Setting it to `../` does seem to work. That solves my issue.

Whether modules should be namespaced or not is a somewhat different discussion I guess. The https://github.com/purescript/purescript/wiki/Style-Guide says modules should follow Haskell namespacing, but doesn't give any detailed advice on what the top-level namespaces should be. Perhaps `Web` is too broad given PureScript's most common domain (browsers) and `UI.React` or something might work better. Though I probably wouldn't change anything before there is broader consensus over the top-level namespaces and whether to have them at all.

Please feel free to close this issue. Thanks for your help!

**Comment by ethul** [comment]
Welcome. I am glad the `--require-path` worked out.

In terms of the namespace, I am unsure what would be best at the moment. But perhaps this can be raised as a separate discussion. Your suggestion of `UI` might work since React is used both on the web and on native. Definitely something to keep in mind and further discuss.
