### ISSUE TITLE
Event Handler Issue

### ISSUE THREAD

**Issue by jasonzoladz** [purescript-contrib/purescript-react#67]
I've wired `purescript-react` with `purescript-rx` for state management, and it works (see https://github.com/jasonzoladz/purescript-react-rxState), but I'm getting this strange console output.

Any thoughts?  It's just a vanilla `onClick` handler.  (https://github.com/jasonzoladz/purescript-react-rxState/blob/master/src/Main.purs#L64)  I'm stumped.

<img width="503" alt="screen shot 2016-03-10 at 3 58 43 pm" src="https://cloud.githubusercontent.com/assets/8467728/13684687/ddc4b630-e6da-11e5-9c70-8d5a5bd1db33.png">

**Comment by jasonzoladz** [comment]
So the bug is right here:  https://github.com/purescript-contrib/purescript-react/blob/master/src/React.js#L114


This:

```javascript
function handle(f) {
  return function(e){
    return f(e)();
  };
};
```

should be:

```javascript
function handle(f) {
  return function(e){
    return f(e);
  };
};
```
I'm submitting the world's second smallest pull request now.

**Comment by ethul** [comment]
Thanks for digging into this. I am not sure we want to remove the `()` though.

We have

```purescript
foreign import handle :: forall eff ev props state result.  (ev -> EventHandlerContext eff props state result) -> EventHandler ev
```

So passing an event to `f` gives us an `EventHandlerContext eff props state result`, which is:

```purescript
type EventHandlerContext eff props state result =
  Eff ( props :: ReactProps
      , refs :: ReactRefs ReadOnly
      , state :: ReactState ReadWrite
      | eff
      ) result
```

So `handle` defined as it is seems to make sense to me because we have to run the `Eff`.

**Comment by jasonzoladz** [comment]
You're right.  The Rx binding needs to fixed instead.  Sorry.  :)

**Comment by ethul** [comment]
Okay, no worries. Thanks for the update.
