### ISSUE TITLE
stopPropagation?

### ISSUE THREAD

**Issue by jasonzoladz** [purescript-contrib/purescript-react#68]
How are you handling `stopPropagation` with this library? (As the `Event` type isn't the same as that exposed by `purescript-dom`.)

**Comment by paf31** [comment]
It's not provided right now, but I'd welcome a PR.

**Comment by paf31** [comment]
Right now, I would use `unsafeCoerce` and `-dom` if I wanted this, but there are safer ways of course.

**Comment by jasonzoladz** [comment]
Cool.  Thanks!
