### ISSUE TITLE
Upgrade to new hotness (React v0.15.0)

### ISSUE THREAD

**Issue by jasonzoladz** [purescript-contrib/purescript-react#75]
No rush.  Just a placeholder for the inevitable upgrade.  New [SVG stuff](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) looks good though...

**Comment by ethul** [comment]
Good call. Thanks for submitting this.

**Comment by sudhirvkumar** [comment]
What is required to upgrade to React v15.2.1?

**Comment by ethul** [comment]
You should be able to use React v15.2.1 with the current release of `purescript-react`. However, the new SVG attributes have not yet been added to `purescript-react`.

**Comment by ethul** [comment]
Closing, since the library is now on v16
