### ISSUE TITLE
Bug (minor):  img element does not take children

### ISSUE THREAD

**Issue by jasonzoladz** [purescript-contrib/purescript-react#76]
Currently, using `img` shows this in the console:

![image](https://cloud.githubusercontent.com/assets/8467728/14864445/e7bd1d62-0c87-11e6-8d28-e8b36ca72f55.png)

It still works, but nobody likes seeing red in development.

The type signature for img should just be:

``` purescript
img :: Array Props -> ReactElement
```

Let me know if you'd like me submit a pull request and I'll put one together this weekend.

**Comment by jasonzoladz** [comment]
This applies to `hr` tags as well.

**Comment by ethul** [comment]
Thanks for pointing this out. Does this also apply to `input` and `link`? There might be others too.

Since this is a breaking change, perhaps we can hang on to this one and bring in such changes at the point when have other breaking changes to make. To try to get them all in at once.

Sound okay?

**Comment by jasonzoladz** [comment]
Sounds good.
