### ISSUE TITLE
"checked" property in React.DOM.Props should be of type "Boolean -> Props"

### ISSUE THREAD

**Issue by foopq** [purescript-contrib/purescript-react#81]
I believe the "checked" property in React.DOM.Props should take a Boolean instead of a String. It feels more idiomatic to use true/false instead of [some string]/[empty string]. Both booleans and strings will work in React, it just feels like booleans are a more natural choice.

**Comment by ethul** [comment]
I agree it would be handy to have a function that uses true/false. Perhaps we could add a new function `checkedBoolean` to support this. It also might be good to run through the props to see if we could do this for other properties as well.

**Comment by ethul** [comment]
Resolved by #88
