### ISSUE TITLE
preventDefault?

### ISSUE THREAD

**Issue by teh** [purescript-contrib/purescript-react#83]
Right now I'm stopping events from propagating like this: 

```
onSubmit ev = do
  (unsafeCoerce ev).preventDefault
  ...    
```

Would you be opposed to me introducing this function (and others from https://facebook.github.io/react/docs/events.html)?

**Comment by jasonzoladz** [comment]
Agree.  I have a similar function.  :(

**Comment by ethul** [comment]
I do think `preventDefault` and friends are useful functions to have. Do you think there is any way to leverage [`preventDefault from purescript-dom`](https://github.com/purescript-contrib/purescript-dom/blob/319bf8998d295109a429fb24c3e6ac9bd3fa945c/src/DOM/Event/Event.purs#L54)?

**Comment by ethul** [comment]
However, since the react library defines its own `Event` type, perhaps defining `preventDefault` separately here does make more sense.
