### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by noullet** [purescript-contrib/purescript-react#89]
Hi,

It seems that the documentation for this library has vanished with this commit:
https://github.com/purescript-contrib/purescript-react/commit/326dbb6e3dec742e2a4eeb73d6fa34c99ed3a50e

Am I missing something?

If it has moved then the link in https://github.com/purescript-contrib/purescript-react/blob/master/README.md should probably be updated to the new location.

**Comment by ethul** [comment]
You're right. Looks like the link should be updated to point to:

https://pursuit.purescript.org/packages/purescript-react

Good catch!

**Comment by NicholasAaronBrady** [comment]
a note that `Module Documentation` is a broken link on https://pursuit.purescript.org/packages/purescript-react as well
