### ISSUE TITLE
what is ReactComponent used for ?

### ISSUE THREAD

**Issue by jhegedus42** [purescript-contrib/purescript-react#91]
https://github.com/purescript-contrib/purescript-react/search?utf8=%E2%9C%93&q=reactcomponent

nothing seems to use it ^

**Comment by ethul** [comment]
It is used by `ReactDOM`:
https://github.com/purescript-contrib/purescript-react-dom/blob/0c2c829843261603917f7edbf2d1338e5bdfc642/src/ReactDOM.purs#L15

**Comment by jhegedus42** [comment]
thanks!

**Comment by ethul** [comment]
Welcome
