### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by paf31** [purescript-contrib/purescript-react#97]
I noticed this repo has never had a LICENSE file which is ... not ideal. Since this package appears as a dependency of several others, I think it's important for it to have a clear license.

The line `"license": "MIT"` was added to `bower.json` fairly early on (commit [e36352cb21a](https://github.com/purescript-contrib/purescript-react/commit/e36352cb21af42346d2898548f1866d1091ca0ea)), which I interpret to mean that this library has been MIT-licensed implicitly since then. I suggest we adopt the MIT license with a copyright notice assigning copyright to "the purescript-react contributors" or something along those lines.

cc @andreypopp @joneshf @ethul Does that sound good?

**Comment by ethul** [comment]
Sounds good to me!

**Comment by joneshf** [comment]
Same.
